spring:
  application:
    name: snippet-searcher-runner
  datasource:
    url: jdbc:postgresql://host.docker.internal:5432/userdb
    username: postgres
    password: password
   # driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8081